name: spacex_web_project
description: A spacex lauches web project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.2
  cupertino_icons: ^1.0.2
  clock: ^1.1.0
  localstorage: ^4.0.0+1
  collection: 1.15.0
  intl: ^0.17.0
  fake_async: 1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/something_went_wrong.jpg
